#require: rubocop-rails
#
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - '**/config/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'config.ru'

  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'
